// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoYQ9mrH01U5QFUzxhM_R9jVCQ7nUzxWM',
    appId: '1:1047711373702:web:8d78756a0178f8613ab407',
    messagingSenderId: '1047711373702',
    projectId: 'app2-f942e',
    authDomain: 'app2-f942e.firebaseapp.com',
    storageBucket: 'app2-f942e.firebasestorage.app',
    measurementId: 'G-T6S7Q3FGLD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuz3P8QEPjrxZetmenGhF9A4OUSL9XDz4',
    appId: '1:1047711373702:android:fd974fd82889278e3ab407',
    messagingSenderId: '1047711373702',
    projectId: 'app2-f942e',
    storageBucket: 'app2-f942e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-zlOEouCMUJUqhYoHx5g2kTQsBDr6TzM',
    appId: '1:1047711373702:ios:e12cb5f9d6ac090d3ab407',
    messagingSenderId: '1047711373702',
    projectId: 'app2-f942e',
    storageBucket: 'app2-f942e.firebasestorage.app',
    iosBundleId: 'com.example.firebaseTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-zlOEouCMUJUqhYoHx5g2kTQsBDr6TzM',
    appId: '1:1047711373702:ios:e12cb5f9d6ac090d3ab407',
    messagingSenderId: '1047711373702',
    projectId: 'app2-f942e',
    storageBucket: 'app2-f942e.firebasestorage.app',
    iosBundleId: 'com.example.firebaseTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoYQ9mrH01U5QFUzxhM_R9jVCQ7nUzxWM',
    appId: '1:1047711373702:web:f4b9ccc6a26797a43ab407',
    messagingSenderId: '1047711373702',
    projectId: 'app2-f942e',
    authDomain: 'app2-f942e.firebaseapp.com',
    storageBucket: 'app2-f942e.firebasestorage.app',
    measurementId: 'G-HPYN06YLC5',
  );
}
